### ISSUE TITLE
OSX Build

### ISSUE THREAD

**Issue by tbruyelle** [remogatto/mandala#4]
I'm trying to build the Mandala samples under OSX.

The issue I have at this time is the OpenGL library links. The following commands fail : 

```
$ go get github.com/remogatto/egl
# pkg-config --cflags egl
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
exit status 1
```

```
$ go get github.com/remogatto/opengles2
# github.com/remogatto/opengles2
../projects/go/src/github.com/remogatto/opengles2/opengles2.go:29:10: fatal error: 'GLES2/gl2.h' file not found
#include <GLES2/gl2.h>
         ^
1 error generated.
```

On OSX the OpenGL libraries are located under `/System/Library/Frameworks/OpenGL.framework`. This is the header files listed in that directory : 

```
$ ls /System/Library/Frameworks/OpenGL.framework/Headers
CGLContext.h        CGLMacro.h      OpenGLAvailability.h    glext.h         glu.h
CGLCurrent.h        CGLRenderers.h      gl.h            gliContext.h        gluContext.h
CGLDevice.h     CGLTypes.h      gl3.h           gliDispatch.h       gluMacro.h
CGLIOSurface.h      OpenGL.h        gl3ext.h        gltypes.h
```

There is no `glew.h` or `gl2.h` so even if I create a symbolic link in `/usr/local/include`, it won't work.

**Comment by tbruyelle** [comment]
Update: I replaced `opengles2` with `go-gl/gl` with the help of `brew install glew`.

**Comment by tbruyelle** [comment]
I manage to build almost all the required deps (appart `remogatto/egl` and `remogatto/opengles2`), now the error is on the `gotask run android`, just after the creation of a madala-template.

```
$ gotask run android
# pkg-config --cflags egl
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
```

I have an error also on `gotask run xorg` : 

```
$ gotask run xorg
# github.com/remogatto/opengles2
../github.com/remogatto/opengles2/opengles2.go:29:10: fatal error: 'GLES2/gl2.h' file not found
#include <GLES2/gl2.h>
         ^
1 error generated.
```

So now I think I have to fix the code inside mandala to replace `opengles` by `go-gl/gl` ?
Also how I'm supposed to replace `egl` ?

Thanks for your help

**Comment by remogatto** [comment]
The egl issue should be fixed now. Could you confirm, please?

For the opengl issue you should replace

``` go
import gl "github.com/remogatto/opengles2"
```

with

``` go
import gl "github.com/go-gl/gl"
```

in <tt>game.go</tt>

Then, in <tt>main.go</tt>, you should comment out this lines:

``` go
glfw.WindowHint(glfw.ClientApi, glfw.OpenglEsApi)
glfw.WindowHint(glfw.ContextVersionMajor, 2)
```

Also, please be sure to rebuild all the stuff with:

<pre>
gotask build xorg --flags "-a"
</pre>

Waiting for your feedback!

**Comment by tbruyelle** [comment]
wow thanks for your reactivity. However it seems the last commit introduced a compile error : 

```
projects/go/src/github.com/remogatto/mandala/sound.go:5: undefined: AudioPlayer
```

**Comment by remogatto** [comment]
The compiler error was due to the lack of sound support on xorg, for now. Please, try to rebuild now.

**Comment by tbruyelle** [comment]
Fine! I managed to run `gotask run xorg` on a simple project generated with the `mandala-templates` command.

I have to fix also the following line in `game.go` : 

``` go
gl.Viewport(0, 0, gl.Sizei(width), gl.Sizei(height))
```

to

``` go
gl.Viewport(0, 0, width, height)
```

There is no type `Sizei` in `go-gl/gl`.

And I have to create a symbolic link for the `glew` library in `/usr/local/include/opt/glew` which links to my `glew` install. This is weird becase I have a exported `$LIBRARY_PATH` variable which should already do the link.

So `gtask run xorg` shows a window with a red background.

---

However `gotask run android` still fails with a `egl` missing error : 

```
$ gotask run android
# pkg-config --cflags egl
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
```

It seems there is still a cgo header somewhere which trigger the `pkg-config --cflags egl`.

**Comment by remogatto** [comment]
Progress, so far :) It would be nice to add support for MacOSX and it seems we're almost here. I'll try to fix the pkg-config issue now.

**Comment by remogatto** [comment]
Try now, remember to issue:

<pre>
gotask build android --flags "-a"
</pre>

Thanks!

**Comment by tbruyelle** [comment]
Thanks to you

I have the same error with `gotask build android --flags "-a"`

**Comment by remogatto** [comment]
Ok, I'll try to uninstall egl from my system and to catch the bug.

**Comment by remogatto** [comment]
Let's try again now :) Be sure to update the egl package!

**Comment by tbruyelle** [comment]
I tried to update the egl package

```
$ go get -u github.com/remogatto/egl
# pkg-config --cflags egl
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
exit status 1
```

But still have the same error, sounds logic since I don't have the egl c library.

**Comment by remogatto** [comment]
This is an expected error if you try to install the package on your system using the Go toolchain in it. However, if you build the package using the GoAndroid toolchain this should not happen because EGL library is included in the android NDK. Try the following steps:

<pre>
cd $GOPATH/src/github.com/remogatto
rm -rf egl
# clone the repo without install the package
git clone https://github.com/remogatto/egl
cd path_with_mandala_examples
# this will build EGL binding using library and include files in NDK
gotask build android --flags "-a"
# this will not build EGL because the desktop app doesn't depend on it 
gotask build xorg --flags "-a" 
</pre>

EDIT: some more comments

**Comment by tbruyelle** [comment]
Wow thanks, it worked perfectly now! 
I was able to build an apk and after deploy on my device it shows the same red background as the xorg app.

What the `--flags "-a"` does ?

**Comment by remogatto** [comment]
Very cool! I'll make some fix to mandala-template in order to support MacOSX in a more clean way. May I ask you to do some test once I'll put the fix upstream? Thanks!

<tt>--flags</tt> pass options to <tt>go build</tt>. So, <tt>-a</tt> force the rebuild of all packages.

**Comment by tbruyelle** [comment]
Of course I will test your fixes.
Thank you

**Comment by remogatto** [comment]
Would you also, please, produce a small report of the steps you followed to install the deps?

**Comment by tbruyelle** [comment]
Yes I will

**Comment by remogatto** [comment]
Thanks!

**Comment by tbruyelle** [comment]
## Quick report of the steps to build on OSX

It comes in addition with the steps described in the README. I will try to pick the items where there is a specific manipulation.

### EGL/OPENGL ES2
- Skip `go get github.com/remogatto/egl`
- Replace `go get github.com/remogatto/opengles2` by `go get github.com/go-gl/gl`. It implies to install also `glew`. You can achieve that easily with `brew install glew`.

### GLFW3

Install GLFW from http://www.glfw.org/. Just download and unzip the sources, then you will need `cmake` to generate the makefiles (`brew install cmake`). Then `cmake . && make && sudo make install` in your glfw directory.

### Xdotool

```
brew install xdotool
```

### mandala-templates

After creating a template, there is a patch to apply in the generated sources : 

``` diff
diff --git a/src/myapp/game.go b/src/myapp/game.go
index bfb9984..621d8f9 100644
--- a/src/myapp/game.go
+++ b/src/myapp/game.go
@@ -6,7 +6,7 @@ import (

        "git.tideland.biz/goas/loop"
        "github.com/remogatto/mandala"
-       gl "github.com/remogatto/opengles2"
+       gl "github.com/go-gl/gl"
 )

 const (
@@ -67,7 +67,7 @@ func renderLoopFunc(control *renderLoopControl) loop.LoopFunc {
                                window.MakeContextCurrent()

                                width, height := window.GetSize()
-                               gl.Viewport(0, 0, gl.Sizei(width), gl.Sizei(height))
+                               gl.Viewport(0, 0, width, height)

                                mandala.Logf("Restarting rendering loop...")
                                ticker = time.NewTicker(time.Duration(1e9 / int(FRAMES_PER_SECOND)))
diff --git a/src/myapp/main.go b/src/myapp/main.go
index 642d0b5..87836da 100644
--- a/src/myapp/main.go
+++ b/src/myapp/main.go
@@ -49,8 +49,8 @@ func main() {
        defer glfw.Terminate()

        // Enable OpenGL ES 2.0.
-       glfw.WindowHint(glfw.ClientApi, glfw.OpenglEsApi)
-       glfw.WindowHint(glfw.ContextVersionMajor, 2)
+       //glfw.WindowHint(glfw.ClientApi, glfw.OpenglEsApi)
+       //glfw.WindowHint(glfw.ContextVersionMajor, 2)
        window, err := glfw.CreateWindow(width, height, "MyApp", nil, nil)
        if err != nil {
                panic(err)
```

After that, `gotask run xorg` will work !

However, I still have an issue with the android build : 

```
$ gotask run android --flags "-a"
# github.com/go-gl/gl
gl.h:2:21: fatal error: GL/glew.h: No such file or directory
compilation terminated.
```

I manage to make it works yesterday on my Mac at home, but not on my job Mac. The error seems to tell there is no `GL/glew.h` in the ndk-toolchain of the Android ndk, is that true ? I should be able to understand the issue when I will go home tonight. I'll check the difference between the 2 machines.

**Comment by remogatto** [comment]
Just pushed some changes on mandala-template. You'll still need to fix the import of OpenGL but you shouldn't need the changes in main.go. Could you confirm please? Thanks!

**Comment by tbruyelle** [comment]
Confirmed. I used the fresh mandala-templates and I just have to update the import and remove the `gl.Sizei`.

**Comment by remogatto** [comment]
Cool! I'll create a wiki page with the instructions to build Mandala on OSX. Which OpenGL version are you using exactly? Thank you very much for your contribution!

**Comment by tbruyelle** [comment]
I displayed `glfw.GetVersionString()` in `main_darwin.go` and it shows

```
3.0.4 Cocoa NSGL chdir menubar
```

**Comment by remogatto** [comment]
Added instructions in a dedicated wiki page. Thanks again!
